Save the ad-hoc throughput test scripts using nuttcp

diff --git a/benchmarks/ad-hoc/iperf3/iperf3_client_MBF b/benchmarks/ad-hoc/iperf3/iperf3_client_MBF
--- a/benchmarks/ad-hoc/iperf3/iperf3_client_MBF
+++ b/benchmarks/ad-hoc/iperf3/iperf3_client_MBF
@@ -3,7 +3,7 @@
 set -euo pipefail
 
 if ! command -v iperf3 >/dev/null 2>&1; then
-  echo "Please first install iperf3" >&2
+  echo "[ERROR] Please first install iperf3" >&2
   exit 1
 fi
 
@@ -25,13 +25,14 @@ for id in {0..7}; do
     --forceflush \
     --udp \
     --bitrate 0 \
+    --time 10 \
     --length 65507 \
     --parallel 2 \
     --set-mss 9216 \
     --zerocopy \
     --omit 2 \
     --repeating-payload \
-    --title "$port" &
+    --title "stream_$port" &
 
   PIDS+=($!)
 done
diff --git a/benchmarks/ad-hoc/iperf3/iperf3_server b/benchmarks/ad-hoc/iperf3/iperf3_server
--- a/benchmarks/ad-hoc/iperf3/iperf3_server
+++ b/benchmarks/ad-hoc/iperf3/iperf3_server
@@ -3,24 +3,26 @@
 set -euo pipefail
 
 if ! command -v iperf3 >/dev/null 2>&1; then
-  echo "Please first install iperf3" >&2
+  echo "[ERROR] Please first install iperf3" >&2
   exit 1
 fi
 
 echo "Cleaning up iperf3 processes..."
 pkill iperf3 || true
+echo
 
-if pgrep iperf3 >/dev/null; then
-  echo "iperf3 process is still running in the background." >&2
+if pgrep --list-full iperf3; then
+  echo "[ERROR] iperf3 process is still running in the background." >&2
   exit 2
 fi
 
 for id in {32..39}; do
   port=510"$id"
   iperf3 \
-    --interval 1 \
+    --interval 2 \
     --affinity "$id" \
     --server \
     --bind 10.10.1.2 \
     --port "$port" &
+  echo "Started iperf3 process $!"
 done
